name: Build

on:
  push:
    paths:
      - 'src/**.md'
      
jobs:
  find-changed-files:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.5
    outputs:
      changed-files: ${{ steps.changed-files.outputs.all_modified_files }}
  convert-changed-files:
    runs-on: ubuntu-18.04
    strategy:
      matrix: ${{ needs.find-changed-files.outputs.changed-files }}
    steps:          
      - uses: actions/checkout@v2      
          
      - uses: docker://pandoc/latex:2.16
        name: build slides
        with:
          args: >-
            -t revealjs 
            --template custom 
            -o output.html 
            input.md 
            --slide-level 2
      
      - name: commit file
        run: |
          git config --global user.name 'Sam Kelley'
          git config --global user.email 'yggilabs@users.noreply.github.com'
          git add output.html
          git commit -am "Automated build"
          git push
