name: Build

on:
  push:
    paths:
      - 'src/**.md'
      
jobs:
  find-changed-files:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Get changed files
        id: changed-files
        run: |
          echo "::set-output name=all_changed_files::[{\"output\":\"docs/we-can-be-healthy.html\",\"input\":\"src/we-can-be-healthy.md\"}]"
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
  convert-changed-files:
    runs-on: ubuntu-18.04
    strategy:
      matrix: 
        file: ${{ fromJson(needs.find-changed-files.outputs.matrix) }}
    steps:          
      - uses: actions/checkout@v2     
      
      - name: set folders
        run: |
          mkdir -p docs        
          
      - uses: docker://pandoc/latex:2.16
        name: build slides
        with:
          args: >-
            -t revealjs 
            --template custom 
            -o ${{ matrix.file.output }}
            ${{ matrix.file.input }}
            --slide-level 2            
      
      - name: commit file
        run: |
          git config --global user.name 'Sam Kelley'
          git config --global user.email 'yggilabs@users.noreply.github.com'
          git add ${{ matrix.file.output }}
          git commit -am "Automated build"
          git push
