name: Build

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: create file list
        id: files_list
        run: |
          echo "Lorem ipsum" > lorem_1.md  # create two example files
          echo "dolor sit amet" > lorem_2.md
          mkdir output  # create output dir
          # this will also include README.md
          echo "::set-output name=files::$(printf '"%s" ' *.md)"

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/result.pdf ${{ steps.files_list.outputs.files }}
          
      - name: commit file
        run: |
          git config --global user.name 'Sam Kelley'
          git config --global user.email 'yggilabs@users.noreply.github.com'
          git add output/result.pdf
          git commit -am "Automated build"
          git push
          
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
