name: Build

on: workflow_dispatch

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:          
      - uses: actions/checkout@v2
      
      - name: template
        run: |          
          echo "---
          ---
          $body$" > custom.revealjs

      - uses: docker://pandoc/latex:2.16
        name: build slides
        with:
          args: >-
            -t revealjs 
            --template custom 
            -o output.html 
            input.md 
            --slide-level 2
      
      - name: commit file
        run: |
          git config --global user.name 'Sam Kelley'
          git config --global user.email 'yggilabs@users.noreply.github.com'
          git add output.html
          git add output.pptx
          git commit -am "Automated build"
          git push
