name: submodule-setup

on: workflow_dispatch
      
jobs:
  submodule-setup:
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2 
      
      - run: |
          git submodule add https://github.com/hakimel/reveal.js.git src/reveal.js
          git config --global user.name 'Sam Kelley'
          git config --global user.email 'yggilabs@users.noreply.github.com'
          git add *
          git commit -am "Automated build"
          git push
